---
title: "AgMiP"
author: "Michiel van Dijk"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
library(pacman)

# Set root
p_load(rprojroot)
root <- find_root(is_rstudio_project)

# Knitr settings
p_load(knitr)
knitr::opts_chunk$set(
  fig.width=12, fig.height=8,
  dpi = 300,
  echo=FALSE, warning=FALSE, message=FALSE,
  fig.path = file.path(root,"FigTabMap/out-"),
  dev = "CairoPNG",
  dev.args = list(CairoPNG = list(bg = "transparent"))
  )


# Pander settings
p_load(pander)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('digits', 2)
panderOptions('round', 2)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

```

```{r load_data, echo = FALSE, message = FALSE}
library(readr)

TOTAL <- read.csv(file.path(root, "\\Cache\\agmip_MAGNET_2017-05-17.csv"))
```

\newpage
# Variable coverage
```{r variable, echo = FALSE, message = FALSE}
xtabs(~ variable + model, data = TOTAL)
```

\newpage
# Region coverage
```{r region, echo = FALSE, message = FALSE}
xtabs(~ region + model, data = TOTAL)
```

\newpage
# Item coverage
```{r item, echo = FALSE, message = FALSE}
xtabs(~ item + variable, data = TOTAL)
```

\newpage
# item x Unit coverage
```{r item_unit, echo = FALSE, message = FALSE}
xtabs(~ unit + item, data = TOTAL)
```

\newpage
# Unit x variable coverage
```{r unit_variable, echo = FALSE, message = FALSE}
xtabs(~ unit + variable, data = TOTAL)
```

\newpage
# Scenario coverage
```{r scenario, echo = FALSE, message = FALSE}
xtabs(~ scenario + model, data = TOTAL)
```
